(function($){
    $(window).load(function(){
        $("#sidebar").mCustomScrollbar({
            scrollButtons:{
                enable:true
            },
        theme:"dark"
    });
    });
})(jQuery);
